services:
  ollama:
    volumes:
      - ollama:/root/.ollama
      - ./data:/data
    container_name: ollama
    pull_policy: if_not_present
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_TAG-latest}
    ports:
      - ${OLLAMA_PORT-11434}:11434

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${WEBUI_PORT-4080}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_AUTH=false'
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}